services:
  db:
    image: postgres:17
    container_name: main-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${POSTGRES_DB_NAMES}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d auth_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:9092,EXTERNAL://localhost:9094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: 'INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk' # รหัส Cluster (บังคับใส่สำหรับโหมด KRaft)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    restart: unless-stopped

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    restart: unless-stopped # Application Services
  auth-service-app:
    build:
      context: .
      dockerfile: backend/services/auth_service/Dockerfile
    container_name: auth-service-app
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - APP_PORT=3001
      - DB_HOST_AUTH=db
      - DB_PORT_AUTH=5432
      - DB_NAME_AUTH=auth_db
      - DB_USER_AUTH=${APP_DB_USER}
      - DB_PASSWORD_AUTH=${APP_DB_PASSWORD}

  product-service-app:
    build:
      context: .
      dockerfile: backend/services/product_service/Dockerfile
    container_name: product-service-app
    ports:
      - "3002:3002"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - APP_PORT=3002
      - DB_HOST_PRODUCT=db
      - DB_PORT_PRODUCT=5432
      - DB_NAME_PRODUCT=product_db
      - DB_USER_PRODUCT=${APP_DB_USER}
      - DB_PASSWORD_PRODUCT=${APP_DB_PASSWORD}
      - KAFKA_BROKERS=kafka:9092
  order-service-app:
    build:
      context: .
      dockerfile: backend/services/order_service/Dockerfile
    container_name: order-service-app
    ports:
      - "3003:3003"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - APP_PORT=3003
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=order_db
      - DB_USER=${APP_DB_USER}
      - DB_PASSWORD=${APP_DB_PASSWORD}
      - KAFKA_BROKERS=kafka:9092
  bff-service-app:
    build: ./backend/bff
    container_name: bff-service-app
    ports:
      - "8080:8080"
    environment:
      - APP_PORT=8080 # Database connection details
      - AUTH_SERVICE_URL=auth-service-app:3001
    depends_on:
      - auth-service-app

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BFF_URL=http://localhost:8080
      - BFF_URL=http://bff-service-app:8080
    depends_on:
      - bff-service-app
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:


