// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: ai_service.proto

package aipb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIChatService_Chat_FullMethodName = "/ai_service.AIChatService/Chat"
)

// AIChatServiceClient is the client API for AIChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIChatServiceClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
}

type aIChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIChatServiceClient(cc grpc.ClientConnInterface) AIChatServiceClient {
	return &aIChatServiceClient{cc}
}

func (c *aIChatServiceClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AIChatService_ServiceDesc.Streams[0], AIChatService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIChatService_ChatClient = grpc.ServerStreamingClient[ChatResponse]

// AIChatServiceServer is the server API for AIChatService service.
// All implementations must embed UnimplementedAIChatServiceServer
// for forward compatibility.
type AIChatServiceServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	mustEmbedUnimplementedAIChatServiceServer()
}

// UnimplementedAIChatServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIChatServiceServer struct{}

func (UnimplementedAIChatServiceServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedAIChatServiceServer) mustEmbedUnimplementedAIChatServiceServer() {}
func (UnimplementedAIChatServiceServer) testEmbeddedByValue()                       {}

// UnsafeAIChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIChatServiceServer will
// result in compilation errors.
type UnsafeAIChatServiceServer interface {
	mustEmbedUnimplementedAIChatServiceServer()
}

func RegisterAIChatServiceServer(s grpc.ServiceRegistrar, srv AIChatServiceServer) {
	// If the following call panics, it indicates UnimplementedAIChatServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIChatService_ServiceDesc, srv)
}

func _AIChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AIChatServiceServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AIChatService_ChatServer = grpc.ServerStreamingServer[ChatResponse]

// AIChatService_ServiceDesc is the grpc.ServiceDesc for AIChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai_service.AIChatService",
	HandlerType: (*AIChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _AIChatService_Chat_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ai_service.proto",
}
